version: '3'
services:
  golosdata-mongo:
    build: .
    links:
    - redis
    environment:
    - MONGO_HOST
    - MONGO_PORT
    - MONGO_DB_NAME
    - DB_USER
    - DB_PWD
    - GOLOS_NODE
    - WORKER
  redis:
    image: redis
